name: Generate ASCII art using neofetch

on: push

jobs:
    ascii_job:
        runs-on:
            - ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v6

            - name: Execute ASCII script
              run: |
                ls -altr
                pwd
                chmod +x ascii-script.sh
                ascii-script.sh       