name: Generate ASCII art using neofetch

on: push

jobs:
    ascii_job:
        runs-on:
            - ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v6

            - name: List the files
              run: ls -altrh

            - name: Execute ASCII Shell script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh       