name: My first action WF

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome Banner
          run: echo "Welcome home darling"

        - name: List the files
          run: la -altrh

        - name: Read the file
          run: cat README.md

        