name: My first action WF

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: CheckOut
          uses: actions/checkout@v6

        - name: Multiline command execution
          run: |
            echo "Welcome home darling"
            ls -altr
            cat README.md
